// -----------------------------------------------------------------------------
// Auto-Generated by:        __   _ __      _  __
//                          / /  (_) /____ | |/_/
//                         / /__/ / __/ -_)>  <
//                        /____/_/\__/\__/_/|_|
//                     Build your hardware, easily!
//                   https://github.com/enjoy-digital/litex
//
// Filename   : digilent_arty_s7.v
// Top        : BaseSoC
// Device     : xc7s50csga324-1
// Hierarchy  : disabled
// LiteX sha1 : 2ad18a345
// Date       : 2026-08-17 06:11:50
//------------------------------------------------------------------------------

`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Module
//------------------------------------------------------------------------------

module digilent_arty_s7 (
    (* dont_touch = "true" *)
    input  wire          clk100,
    input  wire          cpu_reset_n,
    input  wire          serial_rx,
    output reg           serial_tx,
    output wire          user_led0,
    output wire          user_led1,
    output wire          user_led2,
    output wire          user_led3
);


//------------------------------------------------------------------------------
// Hierarchy
//------------------------------------------------------------------------------

/*
BaseSoC
├── crg (_CRG)
│    ├── [BB:BUFG]
│    └── [BB:IBUF]
├── bus (SoCBusHandler)
│    └── _interconnect (InterconnectShared)
│         ├── arbiter (Arbiter)
│         │    └── rr (RoundRobin)
│         ├── decoder (Decoder)
│         └── timeout (Timeout)
│              └── waittimer_0 (WaitTimer) [Gen]
├── csr (SoCCSRHandler)
├── irq (SoCIRQHandler)
├── ctrl (SoCController)
├── cpu (SERV)
│    └── [BB:serv_rf_top]
├── rom (SRAM)
├── sram (SRAM)
├── main_ram (SRAM)
├── identifier (Identifier)
├── uart (UART)
│    ├── ev (EventManager)
│    │    ├── eventsourcelevel_0 (EventSourceLevel) [Gen]
│    │    └── eventsourcelevel_1 (EventSourceLevel) [Gen]
│    ├── phy (RS232PHY)
│    │    ├── tx (RS232PHYTX)
│    │    │    ├── clk_phase_accum (RS232ClkPhaseAccum)
│    │    │    └── fsm (FSM)
│    │    └── rx (RS232PHYRX)
│    │         ├── clk_phase_accum (RS232ClkPhaseAccum)
│    │         └── fsm (FSM)
│    ├── tx_fifo (SyncFIFO)
│    │    └── fifo (SyncFIFOBuffered)
│    │         └── fifo (SyncFIFO)
│    └── rx_fifo (SyncFIFO)
│         └── fifo (SyncFIFOBuffered)
│              └── fifo (SyncFIFO)
├── timer0 (Timer)
│    └── ev (EventManager)
│         └── eventsourceprocess_0 (EventSourceProcess) [Gen]
├── leds (LedChaser)
│    └── waittimer_0 (WaitTimer) [Gen]
├── csr_bridge (Wishbone2CSR)
│    └── fsm (FSM)
├── csr_bankarray (CSRBankArray)
│    ├── csrbank_0 (CSRBank) [Gen]
│    │    ├── csrstorage_0 (CSRStorage) [Gen]
│    │    ├── csrstorage_1 (CSRStorage) [Gen]
│    │    └── csrstatus_0 (CSRStatus) [Gen]
│    ├── sram_0 (SRAM) [Gen]
│    ├── csrbank_1 (CSRBank) [Gen]
│    │    └── csrstorage_0 (CSRStorage) [Gen]
│    ├── csrbank_2 (CSRBank) [Gen]
│    │    ├── csrstorage_0 (CSRStorage) [Gen]
│    │    ├── csrstorage_1 (CSRStorage) [Gen]
│    │    ├── csrstorage_2 (CSRStorage) [Gen]
│    │    ├── csrstorage_3 (CSRStorage) [Gen]
│    │    ├── csrstatus_0 (CSRStatus) [Gen]
│    │    ├── csrstatus_1 (CSRStatus) [Gen]
│    │    ├── csrstatus_2 (CSRStatus) [Gen]
│    │    └── csrstorage_4 (CSRStorage) [Gen]
│    └── csrbank_3 (CSRBank) [Gen]
│         ├── csrstatus_0 (CSRStatus) [Gen]
│         ├── csrstatus_1 (CSRStatus) [Gen]
│         ├── csrstatus_2 (CSRStatus) [Gen]
│         ├── csrstatus_3 (CSRStatus) [Gen]
│         ├── csrstorage_0 (CSRStorage) [Gen]
│         ├── csrstatus_4 (CSRStatus) [Gen]
│         └── csrstatus_5 (CSRStatus) [Gen]
├── csr_interconnect (InterconnectShared)
├── [BB:FDPE]
└── [BB:FDPE]
Legend:
  [Gen]: Auto-generated instance name.
  [BB:NAME]: Blackbox instance (verilog Instance).

*/

//------------------------------------------------------------------------------
// Signals
//------------------------------------------------------------------------------

reg    [31:0] builder_basiclowerer_self = 32'd0;
reg    [19:0] builder_count = 20'd1000000;
wire    [5:0] builder_csr_bankarray_adr;
wire   [31:0] builder_csr_bankarray_csrbank0_bus_errors_r;
reg           builder_csr_bankarray_csrbank0_bus_errors_re = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank0_bus_errors_w;
reg           builder_csr_bankarray_csrbank0_bus_errors_we = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank0_reset_r;
reg           builder_csr_bankarray_csrbank0_reset_re = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank0_reset_w;
reg           builder_csr_bankarray_csrbank0_reset_we = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank0_scratch_r;
reg           builder_csr_bankarray_csrbank0_scratch_re = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank0_scratch_w;
reg           builder_csr_bankarray_csrbank0_scratch_we = 1'd0;
wire          builder_csr_bankarray_csrbank0_sel;
wire    [3:0] builder_csr_bankarray_csrbank1_out_r;
reg           builder_csr_bankarray_csrbank1_out_re = 1'd0;
wire    [3:0] builder_csr_bankarray_csrbank1_out_w;
reg           builder_csr_bankarray_csrbank1_out_we = 1'd0;
wire          builder_csr_bankarray_csrbank1_sel;
wire          builder_csr_bankarray_csrbank2_en_r;
reg           builder_csr_bankarray_csrbank2_en_re = 1'd0;
wire          builder_csr_bankarray_csrbank2_en_w;
reg           builder_csr_bankarray_csrbank2_en_we = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_enable_r;
reg           builder_csr_bankarray_csrbank2_ev_enable_re = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_enable_w;
reg           builder_csr_bankarray_csrbank2_ev_enable_we = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_pending_r;
reg           builder_csr_bankarray_csrbank2_ev_pending_re = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_pending_w;
reg           builder_csr_bankarray_csrbank2_ev_pending_we = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_status_r;
reg           builder_csr_bankarray_csrbank2_ev_status_re = 1'd0;
wire          builder_csr_bankarray_csrbank2_ev_status_w;
reg           builder_csr_bankarray_csrbank2_ev_status_we = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_load_r;
reg           builder_csr_bankarray_csrbank2_load_re = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_load_w;
reg           builder_csr_bankarray_csrbank2_load_we = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_reload_r;
reg           builder_csr_bankarray_csrbank2_reload_re = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_reload_w;
reg           builder_csr_bankarray_csrbank2_reload_we = 1'd0;
wire          builder_csr_bankarray_csrbank2_sel;
wire          builder_csr_bankarray_csrbank2_update_value_r;
reg           builder_csr_bankarray_csrbank2_update_value_re = 1'd0;
wire          builder_csr_bankarray_csrbank2_update_value_w;
reg           builder_csr_bankarray_csrbank2_update_value_we = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_value_r;
reg           builder_csr_bankarray_csrbank2_value_re = 1'd0;
wire   [31:0] builder_csr_bankarray_csrbank2_value_w;
reg           builder_csr_bankarray_csrbank2_value_we = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_enable_r;
reg           builder_csr_bankarray_csrbank3_ev_enable_re = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_enable_w;
reg           builder_csr_bankarray_csrbank3_ev_enable_we = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_pending_r;
reg           builder_csr_bankarray_csrbank3_ev_pending_re = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_pending_w;
reg           builder_csr_bankarray_csrbank3_ev_pending_we = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_status_r;
reg           builder_csr_bankarray_csrbank3_ev_status_re = 1'd0;
wire    [1:0] builder_csr_bankarray_csrbank3_ev_status_w;
reg           builder_csr_bankarray_csrbank3_ev_status_we = 1'd0;
wire          builder_csr_bankarray_csrbank3_rxempty_r;
reg           builder_csr_bankarray_csrbank3_rxempty_re = 1'd0;
wire          builder_csr_bankarray_csrbank3_rxempty_w;
reg           builder_csr_bankarray_csrbank3_rxempty_we = 1'd0;
wire          builder_csr_bankarray_csrbank3_rxfull_r;
reg           builder_csr_bankarray_csrbank3_rxfull_re = 1'd0;
wire          builder_csr_bankarray_csrbank3_rxfull_w;
reg           builder_csr_bankarray_csrbank3_rxfull_we = 1'd0;
wire          builder_csr_bankarray_csrbank3_sel;
wire          builder_csr_bankarray_csrbank3_txempty_r;
reg           builder_csr_bankarray_csrbank3_txempty_re = 1'd0;
wire          builder_csr_bankarray_csrbank3_txempty_w;
reg           builder_csr_bankarray_csrbank3_txempty_we = 1'd0;
wire          builder_csr_bankarray_csrbank3_txfull_r;
reg           builder_csr_bankarray_csrbank3_txfull_re = 1'd0;
wire          builder_csr_bankarray_csrbank3_txfull_w;
reg           builder_csr_bankarray_csrbank3_txfull_we = 1'd0;
wire    [7:0] builder_csr_bankarray_dat_r;
wire   [13:0] builder_csr_bankarray_interface0_bank_bus_adr;
reg    [31:0] builder_csr_bankarray_interface0_bank_bus_dat_r = 32'd0;
wire   [31:0] builder_csr_bankarray_interface0_bank_bus_dat_w;
wire          builder_csr_bankarray_interface0_bank_bus_re;
wire          builder_csr_bankarray_interface0_bank_bus_we;
wire   [13:0] builder_csr_bankarray_interface1_bank_bus_adr;
reg    [31:0] builder_csr_bankarray_interface1_bank_bus_dat_r = 32'd0;
wire   [31:0] builder_csr_bankarray_interface1_bank_bus_dat_w;
wire          builder_csr_bankarray_interface1_bank_bus_re;
wire          builder_csr_bankarray_interface1_bank_bus_we;
wire   [13:0] builder_csr_bankarray_interface2_bank_bus_adr;
reg    [31:0] builder_csr_bankarray_interface2_bank_bus_dat_r = 32'd0;
wire   [31:0] builder_csr_bankarray_interface2_bank_bus_dat_w;
wire          builder_csr_bankarray_interface2_bank_bus_re;
wire          builder_csr_bankarray_interface2_bank_bus_we;
wire   [13:0] builder_csr_bankarray_interface3_bank_bus_adr;
reg    [31:0] builder_csr_bankarray_interface3_bank_bus_dat_r = 32'd0;
wire   [31:0] builder_csr_bankarray_interface3_bank_bus_dat_w;
wire          builder_csr_bankarray_interface3_bank_bus_re;
wire          builder_csr_bankarray_interface3_bank_bus_we;
wire          builder_csr_bankarray_sel;
reg           builder_csr_bankarray_sel_r = 1'd0;
wire   [13:0] builder_csr_bankarray_sram_bus_adr;
reg    [31:0] builder_csr_bankarray_sram_bus_dat_r = 32'd0;
wire   [31:0] builder_csr_bankarray_sram_bus_dat_w;
wire          builder_csr_bankarray_sram_bus_re;
wire          builder_csr_bankarray_sram_bus_we;
reg           builder_csr_data_width = 1'd0;
wire   [13:0] builder_csr_interconnect_adr;
wire   [31:0] builder_csr_interconnect_dat_r;
wire   [31:0] builder_csr_interconnect_dat_w;
wire          builder_csr_interconnect_re;
wire          builder_csr_interconnect_we;
wire          builder_done;
reg           builder_error = 1'd0;
reg           builder_grant = 1'd0;
reg           builder_interface0_ack = 1'd0;
wire   [29:0] builder_interface0_adr;
wire    [1:0] builder_interface0_bte;
wire    [2:0] builder_interface0_cti;
wire          builder_interface0_cyc;
reg    [31:0] builder_interface0_dat_r = 32'd0;
wire   [31:0] builder_interface0_dat_w;
reg           builder_interface0_err = 1'd0;
wire    [3:0] builder_interface0_sel;
wire          builder_interface0_stb;
wire          builder_interface0_we;
reg    [13:0] builder_interface1_adr = 14'd0;
wire   [31:0] builder_interface1_dat_r;
reg    [31:0] builder_interface1_dat_w = 32'd0;
reg           builder_interface1_re = 1'd0;
reg           builder_interface1_we = 1'd0;
reg           builder_next_state = 1'd0;
wire    [1:0] builder_request;
reg    [29:0] builder_rhs_self0 = 30'd0;
reg    [31:0] builder_rhs_self1 = 32'd0;
reg     [3:0] builder_rhs_self2 = 4'd0;
reg           builder_rhs_self3 = 1'd0;
reg           builder_rhs_self4 = 1'd0;
reg           builder_rhs_self5 = 1'd0;
reg     [2:0] builder_rhs_self6 = 3'd0;
reg     [1:0] builder_rhs_self7 = 2'd0;
reg           builder_rs232phyrx_next_state = 1'd0;
reg           builder_rs232phyrx_state = 1'd0;
reg           builder_rs232phytx_next_state = 1'd0;
reg           builder_rs232phytx_state = 1'd0;
reg           builder_shared_ack = 1'd0;
wire   [29:0] builder_shared_adr;
wire    [1:0] builder_shared_bte;
wire    [2:0] builder_shared_cti;
wire          builder_shared_cyc;
reg    [31:0] builder_shared_dat_r = 32'd0;
wire   [31:0] builder_shared_dat_w;
wire          builder_shared_err;
wire    [3:0] builder_shared_sel;
wire          builder_shared_stb;
wire          builder_shared_we;
reg     [3:0] builder_slave_sel = 4'd0;
reg     [3:0] builder_slave_sel_r = 4'd0;
reg           builder_state = 1'd0;
wire          builder_wait;
wire          builder_xilinxasyncresetsynchronizerimpl;
wire          builder_xilinxasyncresetsynchronizerimpl_rst_meta;
(* async_reg = "true", mr_ff = "true", dont_touch = "true" *)
reg           builder_xilinxmultiregimpl0 = 1'd0;
(* async_reg = "true", dont_touch = "true" *)
reg           builder_xilinxmultiregimpl1 = 1'd0;
wire   [14:0] main_adr;
reg           main_adr_burst = 1'd0;
wire          main_bus_error;
reg    [31:0] main_bus_errors = 32'd0;
wire          main_bus_errors_rd_stb;
wire   [31:0] main_bus_errors_status;
reg           main_bus_errors_wr_stb = 1'd0;
reg     [3:0] main_chaser = 4'd0;
wire          main_clk100_buf;
reg    [23:0] main_count = 24'd12500000;
wire          main_cpu_rst;
wire   [31:0] main_dat_r;
wire          main_dbus_ack;
wire   [31:0] main_dbus_adr;
reg     [1:0] main_dbus_bte = 2'd0;
reg     [2:0] main_dbus_cti = 3'd0;
wire          main_dbus_cyc;
wire   [31:0] main_dbus_dat_r;
wire   [31:0] main_dbus_dat_w;
wire          main_dbus_err;
wire    [3:0] main_dbus_sel;
wire          main_dbus_stb;
wire          main_dbus_we;
wire          main_done;
wire          main_ibus_ack;
wire   [31:0] main_ibus_adr;
reg     [1:0] main_ibus_bte = 2'd0;
reg     [2:0] main_ibus_cti = 3'd0;
wire          main_ibus_cyc;
wire   [31:0] main_ibus_dat_r;
reg    [31:0] main_ibus_dat_w = 32'd0;
wire          main_ibus_err;
wire    [3:0] main_ibus_sel;
wire          main_ibus_stb;
reg           main_ibus_we = 1'd0;
wire          main_interface0_adapted_interface_ack;
wire   [29:0] main_interface0_adapted_interface_adr;
wire    [1:0] main_interface0_adapted_interface_bte;
wire    [2:0] main_interface0_adapted_interface_cti;
wire          main_interface0_adapted_interface_cyc;
wire   [31:0] main_interface0_adapted_interface_dat_r;
wire   [31:0] main_interface0_adapted_interface_dat_w;
wire          main_interface0_adapted_interface_err;
wire    [3:0] main_interface0_adapted_interface_sel;
wire          main_interface0_adapted_interface_stb;
wire          main_interface0_adapted_interface_we;
reg           main_interface0_ram_bus_ack = 1'd0;
wire   [29:0] main_interface0_ram_bus_adr;
wire    [1:0] main_interface0_ram_bus_bte;
wire    [2:0] main_interface0_ram_bus_cti;
wire          main_interface0_ram_bus_cyc;
wire   [31:0] main_interface0_ram_bus_dat_r;
wire   [31:0] main_interface0_ram_bus_dat_w;
reg           main_interface0_ram_bus_err = 1'd0;
wire    [3:0] main_interface0_ram_bus_sel;
wire          main_interface0_ram_bus_stb;
wire          main_interface0_ram_bus_we;
wire          main_interface1_adapted_interface_ack;
wire   [29:0] main_interface1_adapted_interface_adr;
wire    [1:0] main_interface1_adapted_interface_bte;
wire    [2:0] main_interface1_adapted_interface_cti;
wire          main_interface1_adapted_interface_cyc;
wire   [31:0] main_interface1_adapted_interface_dat_r;
wire   [31:0] main_interface1_adapted_interface_dat_w;
wire          main_interface1_adapted_interface_err;
wire    [3:0] main_interface1_adapted_interface_sel;
wire          main_interface1_adapted_interface_stb;
wire          main_interface1_adapted_interface_we;
reg           main_interface1_ram_bus_ack = 1'd0;
wire   [29:0] main_interface1_ram_bus_adr;
wire    [1:0] main_interface1_ram_bus_bte;
wire    [2:0] main_interface1_ram_bus_cti;
wire          main_interface1_ram_bus_cyc;
wire   [31:0] main_interface1_ram_bus_dat_r;
wire   [31:0] main_interface1_ram_bus_dat_w;
reg           main_interface1_ram_bus_err = 1'd0;
wire    [3:0] main_interface1_ram_bus_sel;
wire          main_interface1_ram_bus_stb;
wire          main_interface1_ram_bus_we;
reg     [3:0] main_leds = 4'd0;
reg           main_mode = 1'd0;
reg           main_ram_bus_ack = 1'd0;
wire   [29:0] main_ram_bus_adr;
wire    [1:0] main_ram_bus_bte;
wire    [2:0] main_ram_bus_cti;
wire          main_ram_bus_cyc;
wire   [31:0] main_ram_bus_dat_r;
wire   [31:0] main_ram_bus_dat_w;
reg           main_ram_bus_err = 1'd0;
wire    [3:0] main_ram_bus_sel;
wire          main_ram_bus_stb;
wire          main_ram_bus_we;
wire          main_reset;
reg     [1:0] main_reset_storage = 2'd0;
reg           main_reset_wr_stb = 1'd0;
reg           main_rst0 = 1'd0;
reg    [31:0] main_scratch_storage = 32'd305419896;
reg           main_scratch_wr_stb = 1'd0;
reg           main_serial_tx_rs232phytx_next_value1 = 1'd0;
reg           main_serial_tx_rs232phytx_next_value_ce1 = 1'd0;
reg           main_soc_rst = 1'd0;
wire   [10:0] main_sram0_adr;
reg           main_sram0_adr_burst = 1'd0;
wire   [31:0] main_sram0_dat_r;
wire   [31:0] main_sram0_dat_w;
reg     [3:0] main_sram0_we = 4'd0;
wire   [12:0] main_sram1_adr;
reg           main_sram1_adr_burst = 1'd0;
wire   [31:0] main_sram1_dat_r;
wire   [31:0] main_sram1_dat_w;
reg     [3:0] main_sram1_we = 4'd0;
reg     [3:0] main_storage = 4'd0;
reg           main_timer_en_storage = 1'd0;
reg           main_timer_en_wr_stb = 1'd0;
reg           main_timer_enable_storage = 1'd0;
reg           main_timer_enable_wr_stb = 1'd0;
wire          main_timer_irq;
reg    [31:0] main_timer_load_storage = 32'd0;
reg           main_timer_load_wr_stb = 1'd0;
wire          main_timer_pending_rd_stb;
wire          main_timer_pending_status;
reg           main_timer_pending_wr_data = 1'd0;
reg           main_timer_pending_wr_stb = 1'd0;
reg    [31:0] main_timer_reload_storage = 32'd0;
reg           main_timer_reload_wr_stb = 1'd0;
wire          main_timer_status_rd_stb;
wire          main_timer_status_status;
reg           main_timer_status_wr_stb = 1'd0;
reg           main_timer_update_value_storage = 1'd0;
reg           main_timer_update_value_wr_stb = 1'd0;
reg    [31:0] main_timer_value = 32'd0;
wire          main_timer_value_rd_stb;
reg    [31:0] main_timer_value_status = 32'd0;
reg           main_timer_value_wr_stb = 1'd0;
wire          main_timer_zero0;
wire          main_timer_zero1;
wire          main_timer_zero2;
reg           main_timer_zero_clear = 1'd0;
reg           main_timer_zero_pending = 1'd0;
wire          main_timer_zero_status;
wire          main_timer_zero_trigger;
reg           main_timer_zero_trigger_d = 1'd0;
reg     [1:0] main_uart_core_enable_storage = 2'd0;
reg           main_uart_core_enable_wr_stb = 1'd0;
wire          main_uart_core_irq;
wire          main_uart_core_pending_rd_stb;
reg     [1:0] main_uart_core_pending_status = 2'd0;
reg     [1:0] main_uart_core_pending_wr_data = 2'd0;
reg           main_uart_core_pending_wr_stb = 1'd0;
wire          main_uart_core_rx0;
wire          main_uart_core_rx1;
wire          main_uart_core_rx2;
reg           main_uart_core_rx_clear = 1'd0;
reg     [3:0] main_uart_core_rx_count = 4'd0;
reg     [3:0] main_uart_core_rx_count_rs232phyrx_next_value0 = 4'd0;
reg           main_uart_core_rx_count_rs232phyrx_next_value_ce0 = 1'd0;
reg     [7:0] main_uart_core_rx_data = 8'd0;
reg     [7:0] main_uart_core_rx_data_rs232phyrx_next_value1 = 8'd0;
reg           main_uart_core_rx_data_rs232phyrx_next_value_ce1 = 1'd0;
reg           main_uart_core_rx_enable = 1'd0;
reg     [3:0] main_uart_core_rx_fifo_consume = 4'd0;
wire          main_uart_core_rx_fifo_do_read;
wire          main_uart_core_rx_fifo_fifo_in_first;
wire          main_uart_core_rx_fifo_fifo_in_last;
wire    [7:0] main_uart_core_rx_fifo_fifo_in_payload_data;
wire          main_uart_core_rx_fifo_fifo_out_first;
wire          main_uart_core_rx_fifo_fifo_out_last;
wire    [7:0] main_uart_core_rx_fifo_fifo_out_payload_data;
reg     [4:0] main_uart_core_rx_fifo_level0 = 5'd0;
wire    [4:0] main_uart_core_rx_fifo_level1;
reg     [3:0] main_uart_core_rx_fifo_produce = 4'd0;
wire    [3:0] main_uart_core_rx_fifo_rdport_adr;
wire    [9:0] main_uart_core_rx_fifo_rdport_dat_r;
wire          main_uart_core_rx_fifo_rdport_re;
wire          main_uart_core_rx_fifo_re;
reg           main_uart_core_rx_fifo_readable = 1'd0;
reg           main_uart_core_rx_fifo_replace = 1'd0;
wire          main_uart_core_rx_fifo_sink_first;
wire          main_uart_core_rx_fifo_sink_last;
wire    [7:0] main_uart_core_rx_fifo_sink_payload_data;
wire          main_uart_core_rx_fifo_sink_ready;
wire          main_uart_core_rx_fifo_sink_valid;
wire          main_uart_core_rx_fifo_source_first;
wire          main_uart_core_rx_fifo_source_last;
wire    [7:0] main_uart_core_rx_fifo_source_payload_data;
wire          main_uart_core_rx_fifo_source_ready;
wire          main_uart_core_rx_fifo_source_valid;
wire    [9:0] main_uart_core_rx_fifo_syncfifo_din;
wire    [9:0] main_uart_core_rx_fifo_syncfifo_dout;
wire          main_uart_core_rx_fifo_syncfifo_re;
wire          main_uart_core_rx_fifo_syncfifo_readable;
wire          main_uart_core_rx_fifo_syncfifo_we;
wire          main_uart_core_rx_fifo_syncfifo_writable;
reg     [3:0] main_uart_core_rx_fifo_wrport_adr = 4'd0;
wire    [9:0] main_uart_core_rx_fifo_wrport_dat_r;
wire    [9:0] main_uart_core_rx_fifo_wrport_dat_w;
wire          main_uart_core_rx_fifo_wrport_we;
wire          main_uart_core_rx_pending;
reg    [31:0] main_uart_core_rx_phase = 32'd0;
wire          main_uart_core_rx_rx;
reg           main_uart_core_rx_rx_d = 1'd0;
reg           main_uart_core_rx_source_first = 1'd0;
reg           main_uart_core_rx_source_last = 1'd0;
reg     [7:0] main_uart_core_rx_source_payload_data = 8'd0;
wire          main_uart_core_rx_source_ready;
reg           main_uart_core_rx_source_valid = 1'd0;
wire          main_uart_core_rx_status;
reg           main_uart_core_rx_tick = 1'd0;
wire          main_uart_core_rx_trigger;
wire          main_uart_core_rxempty_rd_stb;
wire          main_uart_core_rxempty_status;
reg           main_uart_core_rxempty_wr_stb = 1'd0;
wire          main_uart_core_rxfull_rd_stb;
wire          main_uart_core_rxfull_status;
reg           main_uart_core_rxfull_wr_stb = 1'd0;
wire    [7:0] main_uart_core_rxtx_r;
reg           main_uart_core_rxtx_re = 1'd0;
wire    [7:0] main_uart_core_rxtx_w;
reg           main_uart_core_rxtx_we = 1'd0;
wire          main_uart_core_status_rd_stb;
reg     [1:0] main_uart_core_status_status = 2'd0;
reg           main_uart_core_status_wr_stb = 1'd0;
wire          main_uart_core_tx0;
wire          main_uart_core_tx1;
wire          main_uart_core_tx2;
reg           main_uart_core_tx_clear = 1'd0;
reg     [3:0] main_uart_core_tx_count = 4'd0;
reg     [3:0] main_uart_core_tx_count_rs232phytx_next_value0 = 4'd0;
reg           main_uart_core_tx_count_rs232phytx_next_value_ce0 = 1'd0;
reg     [7:0] main_uart_core_tx_data = 8'd0;
reg     [7:0] main_uart_core_tx_data_rs232phytx_next_value2 = 8'd0;
reg           main_uart_core_tx_data_rs232phytx_next_value_ce2 = 1'd0;
reg           main_uart_core_tx_enable = 1'd0;
reg     [3:0] main_uart_core_tx_fifo_consume = 4'd0;
wire          main_uart_core_tx_fifo_do_read;
wire          main_uart_core_tx_fifo_fifo_in_first;
wire          main_uart_core_tx_fifo_fifo_in_last;
wire    [7:0] main_uart_core_tx_fifo_fifo_in_payload_data;
wire          main_uart_core_tx_fifo_fifo_out_first;
wire          main_uart_core_tx_fifo_fifo_out_last;
wire    [7:0] main_uart_core_tx_fifo_fifo_out_payload_data;
reg     [4:0] main_uart_core_tx_fifo_level0 = 5'd0;
wire    [4:0] main_uart_core_tx_fifo_level1;
reg     [3:0] main_uart_core_tx_fifo_produce = 4'd0;
wire    [3:0] main_uart_core_tx_fifo_rdport_adr;
wire    [9:0] main_uart_core_tx_fifo_rdport_dat_r;
wire          main_uart_core_tx_fifo_rdport_re;
wire          main_uart_core_tx_fifo_re;
reg           main_uart_core_tx_fifo_readable = 1'd0;
reg           main_uart_core_tx_fifo_replace = 1'd0;
reg           main_uart_core_tx_fifo_sink_first = 1'd0;
reg           main_uart_core_tx_fifo_sink_last = 1'd0;
wire    [7:0] main_uart_core_tx_fifo_sink_payload_data;
wire          main_uart_core_tx_fifo_sink_ready;
wire          main_uart_core_tx_fifo_sink_valid;
wire          main_uart_core_tx_fifo_source_first;
wire          main_uart_core_tx_fifo_source_last;
wire    [7:0] main_uart_core_tx_fifo_source_payload_data;
wire          main_uart_core_tx_fifo_source_ready;
wire          main_uart_core_tx_fifo_source_valid;
wire    [9:0] main_uart_core_tx_fifo_syncfifo_din;
wire    [9:0] main_uart_core_tx_fifo_syncfifo_dout;
wire          main_uart_core_tx_fifo_syncfifo_re;
wire          main_uart_core_tx_fifo_syncfifo_readable;
wire          main_uart_core_tx_fifo_syncfifo_we;
wire          main_uart_core_tx_fifo_syncfifo_writable;
reg     [3:0] main_uart_core_tx_fifo_wrport_adr = 4'd0;
wire    [9:0] main_uart_core_tx_fifo_wrport_dat_r;
wire    [9:0] main_uart_core_tx_fifo_wrport_dat_w;
wire          main_uart_core_tx_fifo_wrport_we;
wire          main_uart_core_tx_pending;
reg    [31:0] main_uart_core_tx_phase = 32'd0;
wire          main_uart_core_tx_sink_first;
wire          main_uart_core_tx_sink_last;
wire    [7:0] main_uart_core_tx_sink_payload_data;
reg           main_uart_core_tx_sink_ready = 1'd0;
wire          main_uart_core_tx_sink_valid;
wire          main_uart_core_tx_status;
reg           main_uart_core_tx_tick = 1'd0;
wire          main_uart_core_tx_trigger;
wire          main_uart_core_txempty_rd_stb;
wire          main_uart_core_txempty_status;
reg           main_uart_core_txempty_wr_stb = 1'd0;
wire          main_uart_core_txfull_rd_stb;
wire          main_uart_core_txfull_status;
reg           main_uart_core_txfull_wr_stb = 1'd0;
wire          main_uart_core_uart_sink_first;
wire          main_uart_core_uart_sink_last;
wire    [7:0] main_uart_core_uart_sink_payload_data;
wire          main_uart_core_uart_sink_ready;
wire          main_uart_core_uart_sink_valid;
wire          main_uart_core_uart_source_first;
wire          main_uart_core_uart_source_last;
wire    [7:0] main_uart_core_uart_source_payload_data;
wire          main_uart_core_uart_source_ready;
wire          main_uart_core_uart_source_valid;
wire          main_wait;
reg           main_wr_stb = 1'd0;
wire          sys_clk;
wire          sys_rst;

//------------------------------------------------------------------------------
// Combinatorial Logic
//------------------------------------------------------------------------------

assign main_reset = (main_soc_rst | main_cpu_rst);
always @(*) begin
    main_rst0 = 1'd0;
    if (main_soc_rst) begin
        main_rst0 = 1'd1;
    end
end
assign main_bus_error = builder_error;
assign main_interface0_adapted_interface_dat_w = main_ibus_dat_w;
assign main_ibus_dat_r = main_interface0_adapted_interface_dat_r;
assign main_interface0_adapted_interface_sel = main_ibus_sel;
assign main_interface0_adapted_interface_cyc = main_ibus_cyc;
assign main_interface0_adapted_interface_stb = main_ibus_stb;
assign main_ibus_ack = main_interface0_adapted_interface_ack;
assign main_interface0_adapted_interface_we = main_ibus_we;
assign main_interface0_adapted_interface_cti = main_ibus_cti;
assign main_interface0_adapted_interface_bte = main_ibus_bte;
assign main_ibus_err = main_interface0_adapted_interface_err;
assign main_interface0_adapted_interface_adr = main_ibus_adr[31:2];
assign main_interface1_adapted_interface_dat_w = main_dbus_dat_w;
assign main_dbus_dat_r = main_interface1_adapted_interface_dat_r;
assign main_interface1_adapted_interface_sel = main_dbus_sel;
assign main_interface1_adapted_interface_cyc = main_dbus_cyc;
assign main_interface1_adapted_interface_stb = main_dbus_stb;
assign main_dbus_ack = main_interface1_adapted_interface_ack;
assign main_interface1_adapted_interface_we = main_dbus_we;
assign main_interface1_adapted_interface_cti = main_dbus_cti;
assign main_interface1_adapted_interface_bte = main_dbus_bte;
assign main_dbus_err = main_interface1_adapted_interface_err;
assign main_interface1_adapted_interface_adr = main_dbus_adr[31:2];
assign builder_shared_adr = builder_rhs_self0;
assign builder_shared_dat_w = builder_rhs_self1;
assign builder_shared_sel = builder_rhs_self2;
assign builder_shared_cyc = builder_rhs_self3;
assign builder_shared_stb = builder_rhs_self4;
assign builder_shared_we = builder_rhs_self5;
assign builder_shared_cti = builder_rhs_self6;
assign builder_shared_bte = builder_rhs_self7;
assign main_interface0_adapted_interface_dat_r = builder_shared_dat_r;
assign main_interface1_adapted_interface_dat_r = builder_shared_dat_r;
assign main_interface0_adapted_interface_ack = (builder_shared_ack & (builder_grant == 1'd0));
assign main_interface1_adapted_interface_ack = (builder_shared_ack & (builder_grant == 1'd1));
assign main_interface0_adapted_interface_err = (builder_shared_err & (builder_grant == 1'd0));
assign main_interface1_adapted_interface_err = (builder_shared_err & (builder_grant == 1'd1));
assign builder_request = {main_interface1_adapted_interface_cyc, main_interface0_adapted_interface_cyc};
always @(*) begin
    builder_slave_sel = 4'd0;
    builder_slave_sel[0] = (builder_shared_adr[29:15] == 1'd0);
    builder_slave_sel[1] = (builder_shared_adr[29:11] == 12'h800);
    builder_slave_sel[2] = (builder_shared_adr[29:13] == 16'h8000);
    builder_slave_sel[3] = (builder_shared_adr[29:14] == 16'h8200);
end
assign main_ram_bus_adr = builder_shared_adr;
assign main_ram_bus_dat_w = builder_shared_dat_w;
assign main_ram_bus_sel = builder_shared_sel;
assign main_ram_bus_stb = builder_shared_stb;
assign main_ram_bus_we = builder_shared_we;
assign main_ram_bus_cti = builder_shared_cti;
assign main_ram_bus_bte = builder_shared_bte;
assign main_interface0_ram_bus_adr = builder_shared_adr;
assign main_interface0_ram_bus_dat_w = builder_shared_dat_w;
assign main_interface0_ram_bus_sel = builder_shared_sel;
assign main_interface0_ram_bus_stb = builder_shared_stb;
assign main_interface0_ram_bus_we = builder_shared_we;
assign main_interface0_ram_bus_cti = builder_shared_cti;
assign main_interface0_ram_bus_bte = builder_shared_bte;
assign main_interface1_ram_bus_adr = builder_shared_adr;
assign main_interface1_ram_bus_dat_w = builder_shared_dat_w;
assign main_interface1_ram_bus_sel = builder_shared_sel;
assign main_interface1_ram_bus_stb = builder_shared_stb;
assign main_interface1_ram_bus_we = builder_shared_we;
assign main_interface1_ram_bus_cti = builder_shared_cti;
assign main_interface1_ram_bus_bte = builder_shared_bte;
assign builder_interface0_adr = builder_shared_adr;
assign builder_interface0_dat_w = builder_shared_dat_w;
assign builder_interface0_sel = builder_shared_sel;
assign builder_interface0_stb = builder_shared_stb;
assign builder_interface0_we = builder_shared_we;
assign builder_interface0_cti = builder_shared_cti;
assign builder_interface0_bte = builder_shared_bte;
assign main_ram_bus_cyc = (builder_shared_cyc & builder_slave_sel[0]);
assign main_interface0_ram_bus_cyc = (builder_shared_cyc & builder_slave_sel[1]);
assign main_interface1_ram_bus_cyc = (builder_shared_cyc & builder_slave_sel[2]);
assign builder_interface0_cyc = (builder_shared_cyc & builder_slave_sel[3]);
assign builder_shared_err = (((main_ram_bus_err | main_interface0_ram_bus_err) | main_interface1_ram_bus_err) | builder_interface0_err);
assign builder_wait = ((builder_shared_stb & builder_shared_cyc) & (~builder_shared_ack));
always @(*) begin
    builder_error = 1'd0;
    builder_shared_ack = 1'd0;
    builder_shared_dat_r = 32'd0;
    builder_shared_ack = (((main_ram_bus_ack | main_interface0_ram_bus_ack) | main_interface1_ram_bus_ack) | builder_interface0_ack);
    builder_shared_dat_r = (((({32{builder_slave_sel_r[0]}} & main_ram_bus_dat_r) | ({32{builder_slave_sel_r[1]}} & main_interface0_ram_bus_dat_r)) | ({32{builder_slave_sel_r[2]}} & main_interface1_ram_bus_dat_r)) | ({32{builder_slave_sel_r[3]}} & builder_interface0_dat_r));
    if (builder_done) begin
        builder_shared_dat_r = 32'hffffffff;
        builder_shared_ack = 1'd1;
        builder_error = 1'd1;
    end
end
assign builder_done = (builder_count == 1'd0);
assign main_bus_errors_status = main_bus_errors;
assign main_ibus_stb = main_ibus_cyc;
assign main_ibus_sel = 4'd15;
assign main_dbus_stb = main_dbus_cyc;
assign main_adr = main_ram_bus_adr[14:0];
assign main_ram_bus_dat_r = main_dat_r;
always @(*) begin
    main_sram0_we = 4'd0;
    main_sram0_we[0] = (((main_interface0_ram_bus_cyc & main_interface0_ram_bus_stb) & main_interface0_ram_bus_we) & main_interface0_ram_bus_sel[0]);
    main_sram0_we[1] = (((main_interface0_ram_bus_cyc & main_interface0_ram_bus_stb) & main_interface0_ram_bus_we) & main_interface0_ram_bus_sel[1]);
    main_sram0_we[2] = (((main_interface0_ram_bus_cyc & main_interface0_ram_bus_stb) & main_interface0_ram_bus_we) & main_interface0_ram_bus_sel[2]);
    main_sram0_we[3] = (((main_interface0_ram_bus_cyc & main_interface0_ram_bus_stb) & main_interface0_ram_bus_we) & main_interface0_ram_bus_sel[3]);
end
assign main_sram0_adr = main_interface0_ram_bus_adr[10:0];
assign main_interface0_ram_bus_dat_r = main_sram0_dat_r;
assign main_sram0_dat_w = main_interface0_ram_bus_dat_w;
always @(*) begin
    main_sram1_we = 4'd0;
    main_sram1_we[0] = (((main_interface1_ram_bus_cyc & main_interface1_ram_bus_stb) & main_interface1_ram_bus_we) & main_interface1_ram_bus_sel[0]);
    main_sram1_we[1] = (((main_interface1_ram_bus_cyc & main_interface1_ram_bus_stb) & main_interface1_ram_bus_we) & main_interface1_ram_bus_sel[1]);
    main_sram1_we[2] = (((main_interface1_ram_bus_cyc & main_interface1_ram_bus_stb) & main_interface1_ram_bus_we) & main_interface1_ram_bus_sel[2]);
    main_sram1_we[3] = (((main_interface1_ram_bus_cyc & main_interface1_ram_bus_stb) & main_interface1_ram_bus_we) & main_interface1_ram_bus_sel[3]);
end
assign main_sram1_adr = main_interface1_ram_bus_adr[12:0];
assign main_interface1_ram_bus_dat_r = main_sram1_dat_r;
assign main_sram1_dat_w = main_interface1_ram_bus_dat_w;
assign main_uart_core_uart_sink_valid = main_uart_core_rx_source_valid;
assign main_uart_core_rx_source_ready = main_uart_core_uart_sink_ready;
assign main_uart_core_uart_sink_first = main_uart_core_rx_source_first;
assign main_uart_core_uart_sink_last = main_uart_core_rx_source_last;
assign main_uart_core_uart_sink_payload_data = main_uart_core_rx_source_payload_data;
assign main_uart_core_tx_sink_valid = main_uart_core_uart_source_valid;
assign main_uart_core_uart_source_ready = main_uart_core_tx_sink_ready;
assign main_uart_core_tx_sink_first = main_uart_core_uart_source_first;
assign main_uart_core_tx_sink_last = main_uart_core_uart_source_last;
assign main_uart_core_tx_sink_payload_data = main_uart_core_uart_source_payload_data;
assign main_uart_core_tx_fifo_sink_valid = main_uart_core_rxtx_re;
assign main_uart_core_tx_fifo_sink_payload_data = main_uart_core_rxtx_r;
assign main_uart_core_uart_source_valid = main_uart_core_tx_fifo_source_valid;
assign main_uart_core_tx_fifo_source_ready = main_uart_core_uart_source_ready;
assign main_uart_core_uart_source_first = main_uart_core_tx_fifo_source_first;
assign main_uart_core_uart_source_last = main_uart_core_tx_fifo_source_last;
assign main_uart_core_uart_source_payload_data = main_uart_core_tx_fifo_source_payload_data;
assign main_uart_core_txfull_status = (~main_uart_core_tx_fifo_sink_ready);
assign main_uart_core_txempty_status = (~main_uart_core_tx_fifo_source_valid);
assign main_uart_core_tx_trigger = main_uart_core_tx_fifo_sink_ready;
assign main_uart_core_rx_fifo_sink_valid = main_uart_core_uart_sink_valid;
assign main_uart_core_uart_sink_ready = main_uart_core_rx_fifo_sink_ready;
assign main_uart_core_rx_fifo_sink_first = main_uart_core_uart_sink_first;
assign main_uart_core_rx_fifo_sink_last = main_uart_core_uart_sink_last;
assign main_uart_core_rx_fifo_sink_payload_data = main_uart_core_uart_sink_payload_data;
assign main_uart_core_rxtx_w = main_uart_core_rx_fifo_source_payload_data;
assign main_uart_core_rx_fifo_source_ready = main_uart_core_rx_clear;
assign main_uart_core_rxempty_status = (~main_uart_core_rx_fifo_source_valid);
assign main_uart_core_rxfull_status = (~main_uart_core_rx_fifo_sink_ready);
assign main_uart_core_rx_trigger = main_uart_core_rx_fifo_source_valid;
assign main_uart_core_tx0 = main_uart_core_tx_status;
assign main_uart_core_tx1 = main_uart_core_tx_pending;
always @(*) begin
    main_uart_core_tx_clear = 1'd0;
    if ((main_uart_core_pending_wr_stb & main_uart_core_pending_wr_data[0])) begin
        main_uart_core_tx_clear = 1'd1;
    end
end
assign main_uart_core_rx0 = main_uart_core_rx_status;
assign main_uart_core_rx1 = main_uart_core_rx_pending;
always @(*) begin
    main_uart_core_rx_clear = 1'd0;
    if ((main_uart_core_pending_wr_stb & main_uart_core_pending_wr_data[1])) begin
        main_uart_core_rx_clear = 1'd1;
    end
end
assign main_uart_core_irq = ((main_uart_core_pending_status[0] & main_uart_core_enable_storage[0]) | (main_uart_core_pending_status[1] & main_uart_core_enable_storage[1]));
assign main_uart_core_tx_status = main_uart_core_tx_trigger;
assign main_uart_core_tx_pending = main_uart_core_tx_trigger;
assign main_uart_core_rx_status = main_uart_core_rx_trigger;
assign main_uart_core_rx_pending = main_uart_core_rx_trigger;
always @(*) begin
    builder_rs232phytx_next_state = 1'd0;
    main_serial_tx_rs232phytx_next_value1 = 1'd0;
    main_serial_tx_rs232phytx_next_value_ce1 = 1'd0;
    main_uart_core_tx_count_rs232phytx_next_value0 = 4'd0;
    main_uart_core_tx_count_rs232phytx_next_value_ce0 = 1'd0;
    main_uart_core_tx_data_rs232phytx_next_value2 = 8'd0;
    main_uart_core_tx_data_rs232phytx_next_value_ce2 = 1'd0;
    main_uart_core_tx_enable = 1'd0;
    main_uart_core_tx_sink_ready = 1'd0;
    builder_rs232phytx_next_state = builder_rs232phytx_state;
    case (builder_rs232phytx_state)
        1'd1: begin
            main_uart_core_tx_enable = 1'd1;
            if (main_uart_core_tx_tick) begin
                main_serial_tx_rs232phytx_next_value1 = main_uart_core_tx_data[0];
                main_serial_tx_rs232phytx_next_value_ce1 = 1'd1;
                main_uart_core_tx_count_rs232phytx_next_value0 = (main_uart_core_tx_count + 1'd1);
                main_uart_core_tx_count_rs232phytx_next_value_ce0 = 1'd1;
                main_uart_core_tx_data_rs232phytx_next_value2 = {1'd1, main_uart_core_tx_data[7:1]};
                main_uart_core_tx_data_rs232phytx_next_value_ce2 = 1'd1;
                if ((main_uart_core_tx_count == 4'd9)) begin
                    main_uart_core_tx_sink_ready = 1'd1;
                    builder_rs232phytx_next_state = 1'd0;
                end
            end
        end
        default: begin
            main_uart_core_tx_count_rs232phytx_next_value0 = 1'd0;
            main_uart_core_tx_count_rs232phytx_next_value_ce0 = 1'd1;
            main_serial_tx_rs232phytx_next_value1 = 1'd1;
            main_serial_tx_rs232phytx_next_value_ce1 = 1'd1;
            if (main_uart_core_tx_sink_valid) begin
                main_serial_tx_rs232phytx_next_value1 = 1'd0;
                main_serial_tx_rs232phytx_next_value_ce1 = 1'd1;
                main_uart_core_tx_data_rs232phytx_next_value2 = main_uart_core_tx_sink_payload_data;
                main_uart_core_tx_data_rs232phytx_next_value_ce2 = 1'd1;
                builder_rs232phytx_next_state = 1'd1;
            end
        end
    endcase
end
always @(*) begin
    builder_rs232phyrx_next_state = 1'd0;
    main_uart_core_rx_count_rs232phyrx_next_value0 = 4'd0;
    main_uart_core_rx_count_rs232phyrx_next_value_ce0 = 1'd0;
    main_uart_core_rx_data_rs232phyrx_next_value1 = 8'd0;
    main_uart_core_rx_data_rs232phyrx_next_value_ce1 = 1'd0;
    main_uart_core_rx_enable = 1'd0;
    main_uart_core_rx_source_payload_data = 8'd0;
    main_uart_core_rx_source_valid = 1'd0;
    builder_rs232phyrx_next_state = builder_rs232phyrx_state;
    case (builder_rs232phyrx_state)
        1'd1: begin
            main_uart_core_rx_enable = 1'd1;
            if (main_uart_core_rx_tick) begin
                main_uart_core_rx_count_rs232phyrx_next_value0 = (main_uart_core_rx_count + 1'd1);
                main_uart_core_rx_count_rs232phyrx_next_value_ce0 = 1'd1;
                main_uart_core_rx_data_rs232phyrx_next_value1 = {main_uart_core_rx_rx, main_uart_core_rx_data[7:1]};
                main_uart_core_rx_data_rs232phyrx_next_value_ce1 = 1'd1;
                if ((main_uart_core_rx_count == 4'd9)) begin
                    main_uart_core_rx_source_valid = (main_uart_core_rx_rx == 1'd1);
                    main_uart_core_rx_source_payload_data = main_uart_core_rx_data;
                    builder_rs232phyrx_next_state = 1'd0;
                end
            end
        end
        default: begin
            main_uart_core_rx_count_rs232phyrx_next_value0 = 1'd0;
            main_uart_core_rx_count_rs232phyrx_next_value_ce0 = 1'd1;
            if (((main_uart_core_rx_rx == 1'd0) & (main_uart_core_rx_rx_d == 1'd1))) begin
                builder_rs232phyrx_next_state = 1'd1;
            end
        end
    endcase
end
assign main_uart_core_tx_fifo_syncfifo_din = {main_uart_core_tx_fifo_fifo_in_last, main_uart_core_tx_fifo_fifo_in_first, main_uart_core_tx_fifo_fifo_in_payload_data};
assign {main_uart_core_tx_fifo_fifo_out_last, main_uart_core_tx_fifo_fifo_out_first, main_uart_core_tx_fifo_fifo_out_payload_data} = main_uart_core_tx_fifo_syncfifo_dout;
assign main_uart_core_tx_fifo_sink_ready = main_uart_core_tx_fifo_syncfifo_writable;
assign main_uart_core_tx_fifo_syncfifo_we = main_uart_core_tx_fifo_sink_valid;
assign main_uart_core_tx_fifo_fifo_in_first = main_uart_core_tx_fifo_sink_first;
assign main_uart_core_tx_fifo_fifo_in_last = main_uart_core_tx_fifo_sink_last;
assign main_uart_core_tx_fifo_fifo_in_payload_data = main_uart_core_tx_fifo_sink_payload_data;
assign main_uart_core_tx_fifo_source_valid = main_uart_core_tx_fifo_readable;
assign main_uart_core_tx_fifo_source_first = main_uart_core_tx_fifo_fifo_out_first;
assign main_uart_core_tx_fifo_source_last = main_uart_core_tx_fifo_fifo_out_last;
assign main_uart_core_tx_fifo_source_payload_data = main_uart_core_tx_fifo_fifo_out_payload_data;
assign main_uart_core_tx_fifo_re = main_uart_core_tx_fifo_source_ready;
assign main_uart_core_tx_fifo_syncfifo_re = (main_uart_core_tx_fifo_syncfifo_readable & ((~main_uart_core_tx_fifo_readable) | main_uart_core_tx_fifo_re));
assign main_uart_core_tx_fifo_level1 = (main_uart_core_tx_fifo_level0 + main_uart_core_tx_fifo_readable);
always @(*) begin
    main_uart_core_tx_fifo_wrport_adr = 4'd0;
    if (main_uart_core_tx_fifo_replace) begin
        main_uart_core_tx_fifo_wrport_adr = (main_uart_core_tx_fifo_produce - 1'd1);
    end else begin
        main_uart_core_tx_fifo_wrport_adr = main_uart_core_tx_fifo_produce;
    end
end
assign main_uart_core_tx_fifo_wrport_dat_w = main_uart_core_tx_fifo_syncfifo_din;
assign main_uart_core_tx_fifo_wrport_we = (main_uart_core_tx_fifo_syncfifo_we & (main_uart_core_tx_fifo_syncfifo_writable | main_uart_core_tx_fifo_replace));
assign main_uart_core_tx_fifo_do_read = (main_uart_core_tx_fifo_syncfifo_readable & main_uart_core_tx_fifo_syncfifo_re);
assign main_uart_core_tx_fifo_rdport_adr = main_uart_core_tx_fifo_consume;
assign main_uart_core_tx_fifo_syncfifo_dout = main_uart_core_tx_fifo_rdport_dat_r;
assign main_uart_core_tx_fifo_rdport_re = main_uart_core_tx_fifo_do_read;
assign main_uart_core_tx_fifo_syncfifo_writable = (main_uart_core_tx_fifo_level0 != 5'd16);
assign main_uart_core_tx_fifo_syncfifo_readable = (main_uart_core_tx_fifo_level0 != 1'd0);
assign main_uart_core_rx_fifo_syncfifo_din = {main_uart_core_rx_fifo_fifo_in_last, main_uart_core_rx_fifo_fifo_in_first, main_uart_core_rx_fifo_fifo_in_payload_data};
assign {main_uart_core_rx_fifo_fifo_out_last, main_uart_core_rx_fifo_fifo_out_first, main_uart_core_rx_fifo_fifo_out_payload_data} = main_uart_core_rx_fifo_syncfifo_dout;
assign main_uart_core_rx_fifo_sink_ready = main_uart_core_rx_fifo_syncfifo_writable;
assign main_uart_core_rx_fifo_syncfifo_we = main_uart_core_rx_fifo_sink_valid;
assign main_uart_core_rx_fifo_fifo_in_first = main_uart_core_rx_fifo_sink_first;
assign main_uart_core_rx_fifo_fifo_in_last = main_uart_core_rx_fifo_sink_last;
assign main_uart_core_rx_fifo_fifo_in_payload_data = main_uart_core_rx_fifo_sink_payload_data;
assign main_uart_core_rx_fifo_source_valid = main_uart_core_rx_fifo_readable;
assign main_uart_core_rx_fifo_source_first = main_uart_core_rx_fifo_fifo_out_first;
assign main_uart_core_rx_fifo_source_last = main_uart_core_rx_fifo_fifo_out_last;
assign main_uart_core_rx_fifo_source_payload_data = main_uart_core_rx_fifo_fifo_out_payload_data;
assign main_uart_core_rx_fifo_re = main_uart_core_rx_fifo_source_ready;
assign main_uart_core_rx_fifo_syncfifo_re = (main_uart_core_rx_fifo_syncfifo_readable & ((~main_uart_core_rx_fifo_readable) | main_uart_core_rx_fifo_re));
assign main_uart_core_rx_fifo_level1 = (main_uart_core_rx_fifo_level0 + main_uart_core_rx_fifo_readable);
always @(*) begin
    main_uart_core_rx_fifo_wrport_adr = 4'd0;
    if (main_uart_core_rx_fifo_replace) begin
        main_uart_core_rx_fifo_wrport_adr = (main_uart_core_rx_fifo_produce - 1'd1);
    end else begin
        main_uart_core_rx_fifo_wrport_adr = main_uart_core_rx_fifo_produce;
    end
end
assign main_uart_core_rx_fifo_wrport_dat_w = main_uart_core_rx_fifo_syncfifo_din;
assign main_uart_core_rx_fifo_wrport_we = (main_uart_core_rx_fifo_syncfifo_we & (main_uart_core_rx_fifo_syncfifo_writable | main_uart_core_rx_fifo_replace));
assign main_uart_core_rx_fifo_do_read = (main_uart_core_rx_fifo_syncfifo_readable & main_uart_core_rx_fifo_syncfifo_re);
assign main_uart_core_rx_fifo_rdport_adr = main_uart_core_rx_fifo_consume;
assign main_uart_core_rx_fifo_syncfifo_dout = main_uart_core_rx_fifo_rdport_dat_r;
assign main_uart_core_rx_fifo_rdport_re = main_uart_core_rx_fifo_do_read;
assign main_uart_core_rx_fifo_syncfifo_writable = (main_uart_core_rx_fifo_level0 != 5'd16);
assign main_uart_core_rx_fifo_syncfifo_readable = (main_uart_core_rx_fifo_level0 != 1'd0);
assign main_timer_zero_trigger = (main_timer_value == 1'd0);
assign main_timer_zero0 = main_timer_zero_status;
assign main_timer_zero1 = main_timer_zero_pending;
always @(*) begin
    main_timer_zero_clear = 1'd0;
    if ((main_timer_pending_wr_stb & main_timer_pending_wr_data)) begin
        main_timer_zero_clear = 1'd1;
    end
end
assign main_timer_irq = (main_timer_pending_status & main_timer_enable_storage);
assign main_timer_zero_status = main_timer_zero_trigger;
assign main_wait = (~main_done);
always @(*) begin
    main_leds = 4'd0;
    if ((main_mode == 1'd1)) begin
        main_leds = main_storage;
    end else begin
        main_leds = main_chaser;
    end
end
assign {user_led3, user_led2, user_led1, user_led0} = (main_leds ^ 1'd0);
assign main_done = (main_count == 1'd0);
always @(*) begin
    builder_csr_data_width = 1'd0;
    builder_csr_data_width = 1'd0;
    if ((builder_interface0_sel != 1'd0)) begin
        builder_csr_data_width = 1'd0;
    end
end
always @(*) begin
    builder_interface0_ack = 1'd0;
    builder_interface0_dat_r = 32'd0;
    builder_interface1_adr = 14'd0;
    builder_interface1_dat_w = 32'd0;
    builder_interface1_re = 1'd0;
    builder_interface1_we = 1'd0;
    builder_next_state = 1'd0;
    builder_next_state = builder_state;
    case (builder_state)
        1'd1: begin
            builder_interface0_ack = 1'd1;
            builder_interface0_dat_r = 1'd0;
            case (builder_csr_data_width)
                1'd0: begin
                    builder_interface0_dat_r = builder_interface1_dat_r;
                end
            endcase
            builder_next_state = 1'd0;
        end
        default: begin
            builder_interface1_dat_w = builder_basiclowerer_self;
            if ((builder_interface0_cyc & builder_interface0_stb)) begin
                builder_interface1_adr = builder_interface0_adr;
                builder_interface1_re = ((~builder_interface0_we) & (builder_interface0_sel != 1'd0));
                builder_interface1_we = (builder_interface0_we & (builder_interface0_sel != 1'd0));
                builder_next_state = 1'd1;
            end
        end
    endcase
end
assign builder_csr_bankarray_csrbank0_sel = (builder_csr_bankarray_interface0_bank_bus_adr[13:9] == 1'd0);
assign builder_csr_bankarray_csrbank0_reset_r = builder_csr_bankarray_interface0_bank_bus_dat_w[1:0];
always @(*) begin
    builder_csr_bankarray_csrbank0_reset_re = 1'd0;
    builder_csr_bankarray_csrbank0_reset_we = 1'd0;
    if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd0))) begin
        builder_csr_bankarray_csrbank0_reset_re = builder_csr_bankarray_interface0_bank_bus_we;
        builder_csr_bankarray_csrbank0_reset_we = builder_csr_bankarray_interface0_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank0_scratch_r = builder_csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    builder_csr_bankarray_csrbank0_scratch_re = 1'd0;
    builder_csr_bankarray_csrbank0_scratch_we = 1'd0;
    if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 1'd1))) begin
        builder_csr_bankarray_csrbank0_scratch_re = builder_csr_bankarray_interface0_bank_bus_we;
        builder_csr_bankarray_csrbank0_scratch_we = builder_csr_bankarray_interface0_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank0_bus_errors_r = builder_csr_bankarray_interface0_bank_bus_dat_w;
always @(*) begin
    builder_csr_bankarray_csrbank0_bus_errors_re = 1'd0;
    builder_csr_bankarray_csrbank0_bus_errors_we = 1'd0;
    if ((builder_csr_bankarray_csrbank0_sel & (builder_csr_bankarray_interface0_bank_bus_adr[8:0] == 2'd2))) begin
        builder_csr_bankarray_csrbank0_bus_errors_re = builder_csr_bankarray_interface0_bank_bus_we;
        builder_csr_bankarray_csrbank0_bus_errors_we = builder_csr_bankarray_interface0_bank_bus_re;
    end
end
always @(*) begin
    main_soc_rst = 1'd0;
    if (main_reset_wr_stb) begin
        main_soc_rst = main_reset_storage[0];
    end
end
assign main_cpu_rst = main_reset_storage[1];
assign builder_csr_bankarray_csrbank0_reset_w = main_reset_storage;
assign builder_csr_bankarray_csrbank0_scratch_w = main_scratch_storage;
assign builder_csr_bankarray_csrbank0_bus_errors_w = main_bus_errors_status;
assign main_bus_errors_rd_stb = builder_csr_bankarray_csrbank0_bus_errors_we;
assign builder_csr_bankarray_sel = (builder_csr_bankarray_sram_bus_adr[13:9] == 1'd1);
always @(*) begin
    builder_csr_bankarray_sram_bus_dat_r = 32'd0;
    if (builder_csr_bankarray_sel_r) begin
        builder_csr_bankarray_sram_bus_dat_r = builder_csr_bankarray_dat_r;
    end
end
assign builder_csr_bankarray_adr = builder_csr_bankarray_sram_bus_adr[5:0];
assign builder_csr_bankarray_csrbank1_sel = (builder_csr_bankarray_interface1_bank_bus_adr[13:9] == 2'd2);
assign builder_csr_bankarray_csrbank1_out_r = builder_csr_bankarray_interface1_bank_bus_dat_w[3:0];
always @(*) begin
    builder_csr_bankarray_csrbank1_out_re = 1'd0;
    builder_csr_bankarray_csrbank1_out_we = 1'd0;
    if ((builder_csr_bankarray_csrbank1_sel & (builder_csr_bankarray_interface1_bank_bus_adr[8:0] == 1'd0))) begin
        builder_csr_bankarray_csrbank1_out_re = builder_csr_bankarray_interface1_bank_bus_we;
        builder_csr_bankarray_csrbank1_out_we = builder_csr_bankarray_interface1_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank1_out_w = main_storage;
assign builder_csr_bankarray_csrbank2_sel = (builder_csr_bankarray_interface2_bank_bus_adr[13:9] == 2'd3);
assign builder_csr_bankarray_csrbank2_load_r = builder_csr_bankarray_interface2_bank_bus_dat_w;
always @(*) begin
    builder_csr_bankarray_csrbank2_load_re = 1'd0;
    builder_csr_bankarray_csrbank2_load_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd0))) begin
        builder_csr_bankarray_csrbank2_load_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_load_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_reload_r = builder_csr_bankarray_interface2_bank_bus_dat_w;
always @(*) begin
    builder_csr_bankarray_csrbank2_reload_re = 1'd0;
    builder_csr_bankarray_csrbank2_reload_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 1'd1))) begin
        builder_csr_bankarray_csrbank2_reload_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_reload_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_en_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank2_en_re = 1'd0;
    builder_csr_bankarray_csrbank2_en_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd2))) begin
        builder_csr_bankarray_csrbank2_en_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_en_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_update_value_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank2_update_value_re = 1'd0;
    builder_csr_bankarray_csrbank2_update_value_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 2'd3))) begin
        builder_csr_bankarray_csrbank2_update_value_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_update_value_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_value_r = builder_csr_bankarray_interface2_bank_bus_dat_w;
always @(*) begin
    builder_csr_bankarray_csrbank2_value_re = 1'd0;
    builder_csr_bankarray_csrbank2_value_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd4))) begin
        builder_csr_bankarray_csrbank2_value_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_value_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_ev_status_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank2_ev_status_re = 1'd0;
    builder_csr_bankarray_csrbank2_ev_status_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd5))) begin
        builder_csr_bankarray_csrbank2_ev_status_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_ev_status_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_ev_pending_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank2_ev_pending_re = 1'd0;
    builder_csr_bankarray_csrbank2_ev_pending_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd6))) begin
        builder_csr_bankarray_csrbank2_ev_pending_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_ev_pending_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_ev_enable_r = builder_csr_bankarray_interface2_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank2_ev_enable_re = 1'd0;
    builder_csr_bankarray_csrbank2_ev_enable_we = 1'd0;
    if ((builder_csr_bankarray_csrbank2_sel & (builder_csr_bankarray_interface2_bank_bus_adr[8:0] == 3'd7))) begin
        builder_csr_bankarray_csrbank2_ev_enable_re = builder_csr_bankarray_interface2_bank_bus_we;
        builder_csr_bankarray_csrbank2_ev_enable_we = builder_csr_bankarray_interface2_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank2_load_w = main_timer_load_storage;
assign builder_csr_bankarray_csrbank2_reload_w = main_timer_reload_storage;
assign builder_csr_bankarray_csrbank2_en_w = main_timer_en_storage;
assign builder_csr_bankarray_csrbank2_update_value_w = main_timer_update_value_storage;
assign builder_csr_bankarray_csrbank2_value_w = main_timer_value_status;
assign main_timer_value_rd_stb = builder_csr_bankarray_csrbank2_value_we;
assign main_timer_status_status = main_timer_zero0;
assign builder_csr_bankarray_csrbank2_ev_status_w = main_timer_status_status;
assign main_timer_status_rd_stb = builder_csr_bankarray_csrbank2_ev_status_we;
assign main_timer_pending_status = main_timer_zero1;
assign builder_csr_bankarray_csrbank2_ev_pending_w = main_timer_pending_status;
assign main_timer_pending_rd_stb = builder_csr_bankarray_csrbank2_ev_pending_we;
assign main_timer_zero2 = main_timer_enable_storage;
assign builder_csr_bankarray_csrbank2_ev_enable_w = main_timer_enable_storage;
assign builder_csr_bankarray_csrbank3_sel = (builder_csr_bankarray_interface3_bank_bus_adr[13:9] == 3'd4);
assign main_uart_core_rxtx_r = builder_csr_bankarray_interface3_bank_bus_dat_w[7:0];
always @(*) begin
    main_uart_core_rxtx_re = 1'd0;
    main_uart_core_rxtx_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd0))) begin
        main_uart_core_rxtx_re = builder_csr_bankarray_interface3_bank_bus_we;
        main_uart_core_rxtx_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_txfull_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank3_txfull_re = 1'd0;
    builder_csr_bankarray_csrbank3_txfull_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 1'd1))) begin
        builder_csr_bankarray_csrbank3_txfull_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_txfull_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_rxempty_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank3_rxempty_re = 1'd0;
    builder_csr_bankarray_csrbank3_rxempty_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd2))) begin
        builder_csr_bankarray_csrbank3_rxempty_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_rxempty_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_ev_status_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
    builder_csr_bankarray_csrbank3_ev_status_re = 1'd0;
    builder_csr_bankarray_csrbank3_ev_status_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 2'd3))) begin
        builder_csr_bankarray_csrbank3_ev_status_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_ev_status_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_ev_pending_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
    builder_csr_bankarray_csrbank3_ev_pending_re = 1'd0;
    builder_csr_bankarray_csrbank3_ev_pending_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd4))) begin
        builder_csr_bankarray_csrbank3_ev_pending_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_ev_pending_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_ev_enable_r = builder_csr_bankarray_interface3_bank_bus_dat_w[1:0];
always @(*) begin
    builder_csr_bankarray_csrbank3_ev_enable_re = 1'd0;
    builder_csr_bankarray_csrbank3_ev_enable_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd5))) begin
        builder_csr_bankarray_csrbank3_ev_enable_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_ev_enable_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_txempty_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank3_txempty_re = 1'd0;
    builder_csr_bankarray_csrbank3_txempty_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd6))) begin
        builder_csr_bankarray_csrbank3_txempty_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_txempty_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_rxfull_r = builder_csr_bankarray_interface3_bank_bus_dat_w[0];
always @(*) begin
    builder_csr_bankarray_csrbank3_rxfull_re = 1'd0;
    builder_csr_bankarray_csrbank3_rxfull_we = 1'd0;
    if ((builder_csr_bankarray_csrbank3_sel & (builder_csr_bankarray_interface3_bank_bus_adr[8:0] == 3'd7))) begin
        builder_csr_bankarray_csrbank3_rxfull_re = builder_csr_bankarray_interface3_bank_bus_we;
        builder_csr_bankarray_csrbank3_rxfull_we = builder_csr_bankarray_interface3_bank_bus_re;
    end
end
assign builder_csr_bankarray_csrbank3_txfull_w = main_uart_core_txfull_status;
assign main_uart_core_txfull_rd_stb = builder_csr_bankarray_csrbank3_txfull_we;
assign builder_csr_bankarray_csrbank3_rxempty_w = main_uart_core_rxempty_status;
assign main_uart_core_rxempty_rd_stb = builder_csr_bankarray_csrbank3_rxempty_we;
always @(*) begin
    main_uart_core_status_status = 2'd0;
    main_uart_core_status_status[0] = main_uart_core_tx0;
    main_uart_core_status_status[1] = main_uart_core_rx0;
end
assign builder_csr_bankarray_csrbank3_ev_status_w = main_uart_core_status_status;
assign main_uart_core_status_rd_stb = builder_csr_bankarray_csrbank3_ev_status_we;
always @(*) begin
    main_uart_core_pending_status = 2'd0;
    main_uart_core_pending_status[0] = main_uart_core_tx1;
    main_uart_core_pending_status[1] = main_uart_core_rx1;
end
assign builder_csr_bankarray_csrbank3_ev_pending_w = main_uart_core_pending_status;
assign main_uart_core_pending_rd_stb = builder_csr_bankarray_csrbank3_ev_pending_we;
assign main_uart_core_tx2 = main_uart_core_enable_storage[0];
assign main_uart_core_rx2 = main_uart_core_enable_storage[1];
assign builder_csr_bankarray_csrbank3_ev_enable_w = main_uart_core_enable_storage;
assign builder_csr_bankarray_csrbank3_txempty_w = main_uart_core_txempty_status;
assign main_uart_core_txempty_rd_stb = builder_csr_bankarray_csrbank3_txempty_we;
assign builder_csr_bankarray_csrbank3_rxfull_w = main_uart_core_rxfull_status;
assign main_uart_core_rxfull_rd_stb = builder_csr_bankarray_csrbank3_rxfull_we;
assign builder_csr_interconnect_adr = builder_interface1_adr;
assign builder_csr_interconnect_re = builder_interface1_re;
assign builder_csr_interconnect_we = builder_interface1_we;
assign builder_csr_interconnect_dat_w = builder_interface1_dat_w;
assign builder_interface1_dat_r = builder_csr_interconnect_dat_r;
assign builder_csr_bankarray_interface0_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface1_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface2_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface3_bank_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_sram_bus_adr = builder_csr_interconnect_adr;
assign builder_csr_bankarray_interface0_bank_bus_re = builder_csr_interconnect_re;
assign builder_csr_bankarray_interface1_bank_bus_re = builder_csr_interconnect_re;
assign builder_csr_bankarray_interface2_bank_bus_re = builder_csr_interconnect_re;
assign builder_csr_bankarray_interface3_bank_bus_re = builder_csr_interconnect_re;
assign builder_csr_bankarray_sram_bus_re = builder_csr_interconnect_re;
assign builder_csr_bankarray_interface0_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface1_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface2_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface3_bank_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_sram_bus_we = builder_csr_interconnect_we;
assign builder_csr_bankarray_interface0_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface1_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface2_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_interface3_bank_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_bankarray_sram_bus_dat_w = builder_csr_interconnect_dat_w;
assign builder_csr_interconnect_dat_r = ((((builder_csr_bankarray_interface0_bank_bus_dat_r | builder_csr_bankarray_interface1_bank_bus_dat_r) | builder_csr_bankarray_interface2_bank_bus_dat_r) | builder_csr_bankarray_interface3_bank_bus_dat_r) | builder_csr_bankarray_sram_bus_dat_r);
always @(*) begin
    builder_rhs_self0 = 30'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self0 = main_interface0_adapted_interface_adr;
        end
        default: begin
            builder_rhs_self0 = main_interface1_adapted_interface_adr;
        end
    endcase
end
always @(*) begin
    builder_rhs_self1 = 32'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self1 = main_interface0_adapted_interface_dat_w;
        end
        default: begin
            builder_rhs_self1 = main_interface1_adapted_interface_dat_w;
        end
    endcase
end
always @(*) begin
    builder_rhs_self2 = 4'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self2 = main_interface0_adapted_interface_sel;
        end
        default: begin
            builder_rhs_self2 = main_interface1_adapted_interface_sel;
        end
    endcase
end
always @(*) begin
    builder_rhs_self3 = 1'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self3 = main_interface0_adapted_interface_cyc;
        end
        default: begin
            builder_rhs_self3 = main_interface1_adapted_interface_cyc;
        end
    endcase
end
always @(*) begin
    builder_rhs_self4 = 1'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self4 = main_interface0_adapted_interface_stb;
        end
        default: begin
            builder_rhs_self4 = main_interface1_adapted_interface_stb;
        end
    endcase
end
always @(*) begin
    builder_rhs_self5 = 1'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self5 = main_interface0_adapted_interface_we;
        end
        default: begin
            builder_rhs_self5 = main_interface1_adapted_interface_we;
        end
    endcase
end
always @(*) begin
    builder_rhs_self6 = 3'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self6 = main_interface0_adapted_interface_cti;
        end
        default: begin
            builder_rhs_self6 = main_interface1_adapted_interface_cti;
        end
    endcase
end
always @(*) begin
    builder_rhs_self7 = 2'd0;
    case (builder_grant)
        1'd0: begin
            builder_rhs_self7 = main_interface0_adapted_interface_bte;
        end
        default: begin
            builder_rhs_self7 = main_interface1_adapted_interface_bte;
        end
    endcase
end
always @(*) begin
    builder_basiclowerer_self = 32'd0;
    case (builder_csr_data_width)
        default: begin
            builder_basiclowerer_self = builder_interface0_dat_w;
        end
    endcase
end
assign builder_xilinxasyncresetsynchronizerimpl = ((~cpu_reset_n) | main_rst0);
assign main_uart_core_rx_rx = builder_xilinxmultiregimpl1;


//------------------------------------------------------------------------------
// Synchronous Logic
//------------------------------------------------------------------------------

always @(posedge sys_clk) begin
    case (builder_grant)
        1'd0: begin
            if ((~builder_request[0])) begin
                if (builder_request[1]) begin
                    builder_grant <= 1'd1;
                end
            end
        end
        1'd1: begin
            if ((~builder_request[1])) begin
                if (builder_request[0]) begin
                    builder_grant <= 1'd0;
                end
            end
        end
    endcase
    builder_slave_sel_r <= builder_slave_sel;
    if (builder_wait) begin
        if ((~builder_done)) begin
            builder_count <= (builder_count - 1'd1);
        end
    end else begin
        builder_count <= 20'd1000000;
    end
    if ((main_bus_errors != 32'hffffffff)) begin
        if (main_bus_error) begin
            main_bus_errors <= (main_bus_errors + 1'd1);
        end
    end
    main_ram_bus_ack <= 1'd0;
    if (((main_ram_bus_cyc & main_ram_bus_stb) & ((~main_ram_bus_ack) | main_adr_burst))) begin
        main_ram_bus_ack <= 1'd1;
    end
    main_interface0_ram_bus_ack <= 1'd0;
    if (((main_interface0_ram_bus_cyc & main_interface0_ram_bus_stb) & ((~main_interface0_ram_bus_ack) | main_sram0_adr_burst))) begin
        main_interface0_ram_bus_ack <= 1'd1;
    end
    main_interface1_ram_bus_ack <= 1'd0;
    if (((main_interface1_ram_bus_cyc & main_interface1_ram_bus_stb) & ((~main_interface1_ram_bus_ack) | main_sram1_adr_burst))) begin
        main_interface1_ram_bus_ack <= 1'd1;
    end
    {main_uart_core_tx_tick, main_uart_core_tx_phase} <= 23'd4947802;
    if (main_uart_core_tx_enable) begin
        {main_uart_core_tx_tick, main_uart_core_tx_phase} <= (main_uart_core_tx_phase + 23'd4947802);
    end
    builder_rs232phytx_state <= builder_rs232phytx_next_state;
    if (main_uart_core_tx_count_rs232phytx_next_value_ce0) begin
        main_uart_core_tx_count <= main_uart_core_tx_count_rs232phytx_next_value0;
    end
    if (main_serial_tx_rs232phytx_next_value_ce1) begin
        serial_tx <= main_serial_tx_rs232phytx_next_value1;
    end
    if (main_uart_core_tx_data_rs232phytx_next_value_ce2) begin
        main_uart_core_tx_data <= main_uart_core_tx_data_rs232phytx_next_value2;
    end
    main_uart_core_rx_rx_d <= main_uart_core_rx_rx;
    {main_uart_core_rx_tick, main_uart_core_rx_phase} <= 32'h80000000;
    if (main_uart_core_rx_enable) begin
        {main_uart_core_rx_tick, main_uart_core_rx_phase} <= (main_uart_core_rx_phase + 23'd4947802);
    end
    builder_rs232phyrx_state <= builder_rs232phyrx_next_state;
    if (main_uart_core_rx_count_rs232phyrx_next_value_ce0) begin
        main_uart_core_rx_count <= main_uart_core_rx_count_rs232phyrx_next_value0;
    end
    if (main_uart_core_rx_data_rs232phyrx_next_value_ce1) begin
        main_uart_core_rx_data <= main_uart_core_rx_data_rs232phyrx_next_value1;
    end
    if (main_uart_core_tx_fifo_syncfifo_re) begin
        main_uart_core_tx_fifo_readable <= 1'd1;
    end else begin
        if (main_uart_core_tx_fifo_re) begin
            main_uart_core_tx_fifo_readable <= 1'd0;
        end
    end
    if (((main_uart_core_tx_fifo_syncfifo_we & main_uart_core_tx_fifo_syncfifo_writable) & (~main_uart_core_tx_fifo_replace))) begin
        main_uart_core_tx_fifo_produce <= (main_uart_core_tx_fifo_produce + 1'd1);
    end
    if (main_uart_core_tx_fifo_do_read) begin
        main_uart_core_tx_fifo_consume <= (main_uart_core_tx_fifo_consume + 1'd1);
    end
    if (((main_uart_core_tx_fifo_syncfifo_we & main_uart_core_tx_fifo_syncfifo_writable) & (~main_uart_core_tx_fifo_replace))) begin
        if ((~main_uart_core_tx_fifo_do_read)) begin
            main_uart_core_tx_fifo_level0 <= (main_uart_core_tx_fifo_level0 + 1'd1);
        end
    end else begin
        if (main_uart_core_tx_fifo_do_read) begin
            main_uart_core_tx_fifo_level0 <= (main_uart_core_tx_fifo_level0 - 1'd1);
        end
    end
    if (main_uart_core_rx_fifo_syncfifo_re) begin
        main_uart_core_rx_fifo_readable <= 1'd1;
    end else begin
        if (main_uart_core_rx_fifo_re) begin
            main_uart_core_rx_fifo_readable <= 1'd0;
        end
    end
    if (((main_uart_core_rx_fifo_syncfifo_we & main_uart_core_rx_fifo_syncfifo_writable) & (~main_uart_core_rx_fifo_replace))) begin
        main_uart_core_rx_fifo_produce <= (main_uart_core_rx_fifo_produce + 1'd1);
    end
    if (main_uart_core_rx_fifo_do_read) begin
        main_uart_core_rx_fifo_consume <= (main_uart_core_rx_fifo_consume + 1'd1);
    end
    if (((main_uart_core_rx_fifo_syncfifo_we & main_uart_core_rx_fifo_syncfifo_writable) & (~main_uart_core_rx_fifo_replace))) begin
        if ((~main_uart_core_rx_fifo_do_read)) begin
            main_uart_core_rx_fifo_level0 <= (main_uart_core_rx_fifo_level0 + 1'd1);
        end
    end else begin
        if (main_uart_core_rx_fifo_do_read) begin
            main_uart_core_rx_fifo_level0 <= (main_uart_core_rx_fifo_level0 - 1'd1);
        end
    end
    if (main_timer_en_storage) begin
        if ((main_timer_value == 1'd0)) begin
            main_timer_value <= main_timer_reload_storage;
        end else begin
            main_timer_value <= (main_timer_value - 1'd1);
        end
    end else begin
        main_timer_value <= main_timer_load_storage;
    end
    if (main_timer_update_value_wr_stb) begin
        main_timer_value_status <= main_timer_value;
    end
    if (main_timer_zero_clear) begin
        main_timer_zero_pending <= 1'd0;
    end
    main_timer_zero_trigger_d <= main_timer_zero_trigger;
    if ((main_timer_zero_trigger & (~main_timer_zero_trigger_d))) begin
        main_timer_zero_pending <= 1'd1;
    end
    if (main_done) begin
        main_chaser <= {main_chaser, (~main_chaser[3])};
    end
    if (main_wr_stb) begin
        main_mode <= 1'd1;
    end
    if (main_wait) begin
        if ((~main_done)) begin
            main_count <= (main_count - 1'd1);
        end
    end else begin
        main_count <= 24'd12500000;
    end
    builder_state <= builder_next_state;
    builder_csr_bankarray_interface0_bank_bus_dat_r <= 1'd0;
    if (builder_csr_bankarray_csrbank0_sel) begin
        case (builder_csr_bankarray_interface0_bank_bus_adr[8:0])
            1'd0: begin
                builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_reset_w;
            end
            1'd1: begin
                builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_scratch_w;
            end
            2'd2: begin
                builder_csr_bankarray_interface0_bank_bus_dat_r <= builder_csr_bankarray_csrbank0_bus_errors_w;
            end
        endcase
    end
    if (builder_csr_bankarray_csrbank0_reset_re) begin
        main_reset_storage <= builder_csr_bankarray_csrbank0_reset_r;
    end
    main_reset_wr_stb <= builder_csr_bankarray_csrbank0_reset_re;
    if (builder_csr_bankarray_csrbank0_scratch_re) begin
        main_scratch_storage <= builder_csr_bankarray_csrbank0_scratch_r;
    end
    main_scratch_wr_stb <= builder_csr_bankarray_csrbank0_scratch_re;
    main_bus_errors_wr_stb <= builder_csr_bankarray_csrbank0_bus_errors_re;
    builder_csr_bankarray_sel_r <= builder_csr_bankarray_sel;
    builder_csr_bankarray_interface1_bank_bus_dat_r <= 1'd0;
    if (builder_csr_bankarray_csrbank1_sel) begin
        case (builder_csr_bankarray_interface1_bank_bus_adr[8:0])
            1'd0: begin
                builder_csr_bankarray_interface1_bank_bus_dat_r <= builder_csr_bankarray_csrbank1_out_w;
            end
        endcase
    end
    if (builder_csr_bankarray_csrbank1_out_re) begin
        main_storage <= builder_csr_bankarray_csrbank1_out_r;
    end
    main_wr_stb <= builder_csr_bankarray_csrbank1_out_re;
    builder_csr_bankarray_interface2_bank_bus_dat_r <= 1'd0;
    if (builder_csr_bankarray_csrbank2_sel) begin
        case (builder_csr_bankarray_interface2_bank_bus_adr[8:0])
            1'd0: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_load_w;
            end
            1'd1: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_reload_w;
            end
            2'd2: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_en_w;
            end
            2'd3: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_update_value_w;
            end
            3'd4: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_value_w;
            end
            3'd5: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_status_w;
            end
            3'd6: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_pending_w;
            end
            3'd7: begin
                builder_csr_bankarray_interface2_bank_bus_dat_r <= builder_csr_bankarray_csrbank2_ev_enable_w;
            end
        endcase
    end
    if (builder_csr_bankarray_csrbank2_load_re) begin
        main_timer_load_storage <= builder_csr_bankarray_csrbank2_load_r;
    end
    main_timer_load_wr_stb <= builder_csr_bankarray_csrbank2_load_re;
    if (builder_csr_bankarray_csrbank2_reload_re) begin
        main_timer_reload_storage <= builder_csr_bankarray_csrbank2_reload_r;
    end
    main_timer_reload_wr_stb <= builder_csr_bankarray_csrbank2_reload_re;
    if (builder_csr_bankarray_csrbank2_en_re) begin
        main_timer_en_storage <= builder_csr_bankarray_csrbank2_en_r;
    end
    main_timer_en_wr_stb <= builder_csr_bankarray_csrbank2_en_re;
    if (builder_csr_bankarray_csrbank2_update_value_re) begin
        main_timer_update_value_storage <= builder_csr_bankarray_csrbank2_update_value_r;
    end
    main_timer_update_value_wr_stb <= builder_csr_bankarray_csrbank2_update_value_re;
    main_timer_value_wr_stb <= builder_csr_bankarray_csrbank2_value_re;
    main_timer_status_wr_stb <= builder_csr_bankarray_csrbank2_ev_status_re;
    if (builder_csr_bankarray_csrbank2_ev_pending_re) begin
        main_timer_pending_wr_data <= builder_csr_bankarray_csrbank2_ev_pending_r;
    end
    main_timer_pending_wr_stb <= builder_csr_bankarray_csrbank2_ev_pending_re;
    if (builder_csr_bankarray_csrbank2_ev_enable_re) begin
        main_timer_enable_storage <= builder_csr_bankarray_csrbank2_ev_enable_r;
    end
    main_timer_enable_wr_stb <= builder_csr_bankarray_csrbank2_ev_enable_re;
    builder_csr_bankarray_interface3_bank_bus_dat_r <= 1'd0;
    if (builder_csr_bankarray_csrbank3_sel) begin
        case (builder_csr_bankarray_interface3_bank_bus_adr[8:0])
            1'd0: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= main_uart_core_rxtx_w;
            end
            1'd1: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_txfull_w;
            end
            2'd2: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_rxempty_w;
            end
            2'd3: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_status_w;
            end
            3'd4: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_pending_w;
            end
            3'd5: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_ev_enable_w;
            end
            3'd6: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_txempty_w;
            end
            3'd7: begin
                builder_csr_bankarray_interface3_bank_bus_dat_r <= builder_csr_bankarray_csrbank3_rxfull_w;
            end
        endcase
    end
    main_uart_core_txfull_wr_stb <= builder_csr_bankarray_csrbank3_txfull_re;
    main_uart_core_rxempty_wr_stb <= builder_csr_bankarray_csrbank3_rxempty_re;
    main_uart_core_status_wr_stb <= builder_csr_bankarray_csrbank3_ev_status_re;
    if (builder_csr_bankarray_csrbank3_ev_pending_re) begin
        main_uart_core_pending_wr_data <= builder_csr_bankarray_csrbank3_ev_pending_r;
    end
    main_uart_core_pending_wr_stb <= builder_csr_bankarray_csrbank3_ev_pending_re;
    if (builder_csr_bankarray_csrbank3_ev_enable_re) begin
        main_uart_core_enable_storage <= builder_csr_bankarray_csrbank3_ev_enable_r;
    end
    main_uart_core_enable_wr_stb <= builder_csr_bankarray_csrbank3_ev_enable_re;
    main_uart_core_txempty_wr_stb <= builder_csr_bankarray_csrbank3_txempty_re;
    main_uart_core_rxfull_wr_stb <= builder_csr_bankarray_csrbank3_rxfull_re;
    if (sys_rst) begin
        main_reset_storage <= 2'd0;
        main_reset_wr_stb <= 1'd0;
        main_scratch_storage <= 32'd305419896;
        main_scratch_wr_stb <= 1'd0;
        main_bus_errors_wr_stb <= 1'd0;
        main_bus_errors <= 32'd0;
        main_ram_bus_ack <= 1'd0;
        main_interface0_ram_bus_ack <= 1'd0;
        main_interface1_ram_bus_ack <= 1'd0;
        serial_tx <= 1'd1;
        main_uart_core_tx_tick <= 1'd0;
        main_uart_core_rx_tick <= 1'd0;
        main_uart_core_rx_rx_d <= 1'd0;
        main_uart_core_txfull_wr_stb <= 1'd0;
        main_uart_core_rxempty_wr_stb <= 1'd0;
        main_uart_core_status_wr_stb <= 1'd0;
        main_uart_core_pending_wr_stb <= 1'd0;
        main_uart_core_pending_wr_data <= 2'd0;
        main_uart_core_enable_storage <= 2'd0;
        main_uart_core_enable_wr_stb <= 1'd0;
        main_uart_core_txempty_wr_stb <= 1'd0;
        main_uart_core_rxfull_wr_stb <= 1'd0;
        main_uart_core_tx_fifo_readable <= 1'd0;
        main_uart_core_tx_fifo_level0 <= 5'd0;
        main_uart_core_tx_fifo_produce <= 4'd0;
        main_uart_core_tx_fifo_consume <= 4'd0;
        main_uart_core_rx_fifo_readable <= 1'd0;
        main_uart_core_rx_fifo_level0 <= 5'd0;
        main_uart_core_rx_fifo_produce <= 4'd0;
        main_uart_core_rx_fifo_consume <= 4'd0;
        main_timer_load_storage <= 32'd0;
        main_timer_load_wr_stb <= 1'd0;
        main_timer_reload_storage <= 32'd0;
        main_timer_reload_wr_stb <= 1'd0;
        main_timer_en_storage <= 1'd0;
        main_timer_en_wr_stb <= 1'd0;
        main_timer_update_value_storage <= 1'd0;
        main_timer_update_value_wr_stb <= 1'd0;
        main_timer_value_status <= 32'd0;
        main_timer_value_wr_stb <= 1'd0;
        main_timer_zero_pending <= 1'd0;
        main_timer_zero_trigger_d <= 1'd0;
        main_timer_status_wr_stb <= 1'd0;
        main_timer_pending_wr_stb <= 1'd0;
        main_timer_pending_wr_data <= 1'd0;
        main_timer_enable_storage <= 1'd0;
        main_timer_enable_wr_stb <= 1'd0;
        main_timer_value <= 32'd0;
        main_storage <= 4'd0;
        main_wr_stb <= 1'd0;
        main_chaser <= 4'd0;
        main_mode <= 1'd0;
        main_count <= 24'd12500000;
        builder_grant <= 1'd0;
        builder_slave_sel_r <= 4'd0;
        builder_count <= 20'd1000000;
        builder_csr_bankarray_sel_r <= 1'd0;
        builder_rs232phytx_state <= 1'd0;
        builder_rs232phyrx_state <= 1'd0;
        builder_state <= 1'd0;
    end
    builder_xilinxmultiregimpl0 <= serial_rx;
    builder_xilinxmultiregimpl1 <= builder_xilinxmultiregimpl0;
end


//------------------------------------------------------------------------------
// Specialized Logic
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Instance IBUF of IBUF Module.
//------------------------------------------------------------------------------
IBUF IBUF(
	// Inputs.
	.I (clk100),

	// Outputs.
	.O (main_clk100_buf)
);

//------------------------------------------------------------------------------
// Instance BUFG of BUFG Module.
//------------------------------------------------------------------------------
BUFG BUFG(
	// Inputs.
	.I (main_clk100_buf),

	// Outputs.
	.O (sys_clk)
);

//------------------------------------------------------------------------------
// Memory rom: 5891-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [31:0] rom[0:5890];
initial begin
	$readmemh("digilent_arty_s7_rom.init", rom);
end
reg [31:0] rom_dat0;
always @(posedge sys_clk) begin
	rom_dat0 <= rom[main_adr];
end
assign main_dat_r = rom_dat0;


//------------------------------------------------------------------------------
// Memory sram: 2048-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8
reg [31:0] sram[0:2047];
initial begin
	$readmemh("digilent_arty_s7_sram.init", sram);
end
reg [10:0] sram_adr0;
always @(posedge sys_clk) begin : mem_write_block
	integer we_index;
	for(we_index = 0; we_index < 4; we_index=we_index+1)
		if (main_sram0_we[we_index])
			sram[main_sram0_adr][we_index*8 +: 8] <= main_sram0_dat_w[we_index*8 +: 8];
	sram_adr0 <= main_sram0_adr;
end
assign main_sram0_dat_r = sram[sram_adr0];


//------------------------------------------------------------------------------
// Memory main_ram: 8192-words x 32-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Write-First | Write-Granularity: 8
reg [31:0] main_ram[0:8191];
initial begin
	$readmemh("digilent_arty_s7_main_ram.init", main_ram);
end
reg [12:0] main_ram_adr0;
always @(posedge sys_clk) begin : mem_write_block_1
	integer we_index_1;
	for(we_index_1 = 0; we_index_1 < 4; we_index_1=we_index_1+1)
		if (main_sram1_we[we_index_1])
			main_ram[main_sram1_adr][we_index_1*8 +: 8] <= main_sram1_dat_w[we_index_1*8 +: 8];
	main_ram_adr0 <= main_sram1_adr;
end
assign main_sram1_dat_r = main_ram[main_ram_adr0];


//------------------------------------------------------------------------------
// Memory mem: 41-words x 8-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: ---- | 
reg [7:0] mem[0:40];
initial begin
	$readmemh("digilent_arty_s7_mem.init", mem);
end
reg [7:0] mem_dat0;
always @(posedge sys_clk) begin
	mem_dat0 <= mem[builder_csr_bankarray_adr];
end
assign builder_csr_bankarray_dat_r = mem_dat0;


//------------------------------------------------------------------------------
// Memory storage: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage[0:15];
reg [9:0] storage_dat0;
reg [9:0] storage_dat1;
always @(posedge sys_clk) begin
	if (main_uart_core_tx_fifo_wrport_we)
		storage[main_uart_core_tx_fifo_wrport_adr] <= main_uart_core_tx_fifo_wrport_dat_w;
	storage_dat0 <= storage[main_uart_core_tx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (main_uart_core_tx_fifo_rdport_re) begin
		storage_dat1 <= storage[main_uart_core_tx_fifo_rdport_adr];
	end
end
assign main_uart_core_tx_fifo_wrport_dat_r = storage_dat0;
assign main_uart_core_tx_fifo_rdport_dat_r = storage_dat1;


//------------------------------------------------------------------------------
// Memory storage_1: 16-words x 10-bit
//------------------------------------------------------------------------------
// Port 0 | Read: Sync  | Write: Sync | Mode: Read-First 
// Port 1 | Read: Sync  | Write: ---- | 
reg [9:0] storage_1[0:15];
reg [9:0] storage_1_dat0;
reg [9:0] storage_1_dat1;
always @(posedge sys_clk) begin
	if (main_uart_core_rx_fifo_wrport_we)
		storage_1[main_uart_core_rx_fifo_wrport_adr] <= main_uart_core_rx_fifo_wrport_dat_w;
	storage_1_dat0 <= storage_1[main_uart_core_rx_fifo_wrport_adr];
end
always @(posedge sys_clk) begin
	if (main_uart_core_rx_fifo_rdport_re) begin
		storage_1_dat1 <= storage_1[main_uart_core_rx_fifo_rdport_adr];
	end
end
assign main_uart_core_rx_fifo_wrport_dat_r = storage_1_dat0;
assign main_uart_core_rx_fifo_rdport_dat_r = storage_1_dat1;


//------------------------------------------------------------------------------
// Instance serv_rf_top of serv_rf_top Module.
//------------------------------------------------------------------------------
serv_rf_top #(
	// Parameters.
	.RESET_PC (1'd0)
) serv_rf_top (
	// Inputs.
	.clk         (sys_clk),
	.i_dbus_ack  (main_dbus_ack),
	.i_dbus_rdt  (main_dbus_dat_r),
	.i_ibus_ack  (main_ibus_ack),
	.i_ibus_rdt  (main_ibus_dat_r),
	.i_rst       ((sys_rst | main_reset)),
	.i_timer_irq (1'd0),

	// Outputs.
	.o_dbus_adr  (main_dbus_adr),
	.o_dbus_cyc  (main_dbus_cyc),
	.o_dbus_dat  (main_dbus_dat_w),
	.o_dbus_sel  (main_dbus_sel),
	.o_dbus_we   (main_dbus_we),
	.o_ibus_adr  (main_ibus_adr),
	.o_ibus_cyc  (main_ibus_cyc)
);

(* ars_ff1 = "true", async_reg = "true" *)
//------------------------------------------------------------------------------
// Instance FDPE of FDPE Module.
//------------------------------------------------------------------------------
FDPE #(
	// Parameters.
	.INIT (1'd1)
) FDPE (
	// Inputs.
	.C   (sys_clk),
	.CE  (1'd1),
	.D   (1'd0),
	.PRE (builder_xilinxasyncresetsynchronizerimpl),

	// Outputs.
	.Q   (builder_xilinxasyncresetsynchronizerimpl_rst_meta)
);

(* ars_ff2 = "true", async_reg = "true" *)
//------------------------------------------------------------------------------
// Instance FDPE_1 of FDPE Module.
//------------------------------------------------------------------------------
FDPE #(
	// Parameters.
	.INIT (1'd1)
) FDPE_1 (
	// Inputs.
	.C   (sys_clk),
	.CE  (1'd1),
	.D   (builder_xilinxasyncresetsynchronizerimpl_rst_meta),
	.PRE (builder_xilinxasyncresetsynchronizerimpl),

	// Outputs.
	.Q   (sys_rst)
);

endmodule

// -----------------------------------------------------------------------------
//  Auto-Generated by LiteX on 2026-08-17 06:11:50.
//------------------------------------------------------------------------------
