FAMILY  = spartan7
PART    = xc7s50csga324-1
BOARD   = arty_s7_50
PROJECT = digilent_arty_s7
CHIPDB  = ${SPARTAN7_CHIPDB}

ADDITIONAL_SOURCES=../serv/serv_aligner.v \
../serv/serv_alu.v \
../serv/serv_bufreg.v \
../serv/serv_bufreg2.v \
../serv/serv_compdec.v \
../serv/serv_csr.v \
../serv/serv_ctrl.v \
../serv/serv_decode.v \
../serv/serv_immdec.v \
../serv/serv_mem_if.v \
../serv/serv_rf_if.v \
../serv/serv_rf_ram.v \
../serv/serv_rf_ram_if.v \
../serv/serv_rf_top.v \
../serv/serv_state.v \
../serv/serv_synth_wrapper.v \
../serv/serv_top.v

include ../openXC7.mk
