FAMILY  = spartan7
PART    = xc7s50csga324-1
BOARD   = arty_s7_50
PROJECT = digilent_arty_s7

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES=${VEXRISCV}/VexRiscv.v

# PNR_ARGS = --freq 80

include ../openXC7.mk
