create_clock -period 10.000 -name clk [get_ports clk]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN T6 [get_ports we]
set_property PACKAGE_PIN T14 [get_ports d]
set_property PACKAGE_PIN B13 [get_ports o]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports we]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports o]
