FAMILY  = kintex7
PART    = xc7k325tffg676-1
BOARD   = stlv7325
PROJECT = sitlinv_stlv7325
CHIPDB  = ${KINTEX7_CHIPDB}

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES=${VEXRISCV}/VexRiscv.v

include ../openXC7.mk

