set_property PACKAGE_PIN T14 [get_ports a]
set_property PACKAGE_PIN T15 [get_ports b]
set_property PACKAGE_PIN B13 [get_ports y]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports y]
