# Digilent Arty A7 (xc7a35tcsg324 / xc7a100tcsg324 share this pinout)
set_property LOC E3 [get_ports {clk100}]
set_property IOSTANDARD LVCMOS33 [get_ports {clk100}]
set_property LOC C2 [get_ports {cpu_reset_n}]
set_property IOSTANDARD LVCMOS33 [get_ports {cpu_reset_n}]

set_property LOC A8 [get_ports {sw[0]}]
set_property LOC C11 [get_ports {sw[1]}]
set_property LOC C10 [get_ports {sw[2]}]
set_property LOC A10 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]

set_property LOC H5 [get_ports {led[0]}]
set_property LOC J5 [get_ports {led[1]}]
set_property LOC T9 [get_ports {led[2]}]
set_property LOC T10 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]

create_clock -name clk100 -period 10.0 [get_ports clk100]
