// xc7z010clg400 (Arty Z7): btn[1] as clock, btn[0] as active-low reset,
// the four green LEDs as outputs.
create_clock -period 5.000 -name clk [get_ports clk]
set_property PACKAGE_PIN T15 [get_ports clk]
set_property PACKAGE_PIN T14 [get_ports rst_n]
set_property PACKAGE_PIN W14 [get_ports {led[0]}]
set_property PACKAGE_PIN W13 [get_ports {led[1]}]
set_property PACKAGE_PIN V15 [get_ports {led[2]}]
set_property PACKAGE_PIN W15 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
