FAMILY  = kintex7
PART    = xc7k325tffg900-2
BOARD   = kc705
PROJECT = xilinx_kc705
CHIPDB  = ${KINTEX7_CHIPDB}

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES=${VEXRISCV}/VexRiscv.v

PNR_ARGS = --timing-allow-fail

include ../openXC7.mk
