FAMILY  = artix7
PART    = xc7a35tfgg484-2
PROJECT = litex_pcie
CHIPDB  = ${ARTIX7_CHIPDB}

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES=${VEXRISCV}/VexRiscv.v

PNR_ARGS = --timing-allow-fail

include ../openXC7.mk
