FAMILY  = artix7
PART    = xc7a100tfgg676-1
PROJECT = qmtech_artix7_fgg676
JTAG_LINK = -c dirtyJtag
CHIPDB  = ${ARTIX7_CHIPDB}

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES = ${VEXRISCV}/VexRiscv.v

PNR_ARGS = --timing-allow-fail

include ../openXC7.mk
