FAMILY  = kintex7
PART    = xc7k160tffg676-2
BOARD   = qmtechKintex7
PROJECT = enclustra_mercury_kx2
CHIPDB  = ${KINTEX7_CHIPDB}

VEXRISCV=../vexriscv
ADDITIONAL_SOURCES = ${VEXRISCV}/VexRiscv.v

include ../openXC7.mk
