#!/bin/bash -e

git clone https://github.com/regymm/GenZ
PYTHONPATH=GenZ python3 ./sdboot.py

# Prepare BSP folder for PYNQ-Z1
git clone https://github.com/regymm/embeddedsw --depth=1
cp -a embeddedsw/lib/sw_apps/zynq_fsbl/misc/{muzy4,pynqz1}
# Copy the BSP files generated by GenZ
cp ps7_init_sdboot/* embeddedsw/lib/sw_apps/zynq_fsbl/misc/pynqz1

make BOARD=pynqz1 "CFLAGS=-DAXI_TEST" -C embeddedsw/lib/sw_apps/hello_world/src
make BOARD=pynqz1 "CFLAGS=-DFSBL_DEBUG_INFO -DNODDR" -C embeddedsw/lib/sw_apps/zynq_fsbl/src

# Prepare BOOT.BIN for SD Boot
git clone https://github.com/antmicro/zynq-mkbootimage --depth=1
make -C zynq-mkbootimage

# Prepare bif
cat > output.bif << EOF
the_ROM_image:
{
	[bootloader]embeddedsw/lib/sw_apps/zynq_fsbl/src/fsbl.elf
	ps7_axi_blinky.bit
	embeddedsw/lib/sw_apps/hello_world/src/hello-world.elf
}
EOF

# Generate BOOT.BIN
./zynq-mkbootimage/mkbootimage output.bif BOOT.BIN
